Repository replit-discord/replit-desktop, pull requests merged in 2021-02, with the labels that each got.

#116 Create feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: markdown

#115 Update README and Contrib Guide
  .github/CONTRIBUTING.md
  README.md
Labels: markdown

#117 Create bug_report.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: markdown

#124 spotandjake theming update 1
  .eslintrc.js
  .github/workflows/eslint.yml
  package-lock.json
  package.json
  src/app/app.ts
  src/app/menu/appMenuSetup.ts
  src/app/themeHandler/Themes.ts
  src/app/themeHandler/custom.html
  src/app/themeHandler/edit.html
  src/app/themeHandler/themeHandler.ts
  src/app/themeHandler/themeTemplate.ts
  src/app/themeHandler/themes.html
Labels: Merge Request, enhancement

#142 Clean up aisle 6
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  logos/fetch-icons.js
  package-lock.json
  package.json
  src/app/app.ts
  src/app/discordHandler.ts
  src/app/menu/appMenuSetup.ts
  src/app/offline.html
  src/app/popoutHandler/popoutHandler.ts
  src/app/settingHandler.ts
  src/app/themeHandler/Editor/Editor.html
  src/app/themeHandler/themeHandler.ts
  src/common.ts
  src/launcher/launcher.html
  src/preload/auth.ts
  src/prompt/index.ts
  src/prompt/page/darkTheme.css
  src/prompt/page/lightTheme.css
  src/prompt/page/prompt.html
  src/prompt/page/prompt.js
Labels: dependencies, enhancement

#147 Spotandjake dev
  src/app/app.ts
  src/app/discordHandler.ts
  src/app/languages.ts
  src/app/settingHandler.ts
  src/launcher/launcher.ts
  src/main.ts
  src/preload/aceFix.ts
Labels: enhancement
